CREATE TABLE [sid].[Account_Processing_Manual] (
    [LoadId]                                            VARCHAR (100)   NOT NULL,
    [ID]                                                INT             NOT NULL,
    [Action]                                            NVARCHAR (5)    NOT NULL,
    [IsApproved]                                        VARCHAR (3)     NOT NULL,
    [ApprovalNote]                                      VARCHAR (2000)  NULL,
    [GroupNo]                                           NVARCHAR (50)   NOT NULL,
    [GroupName]                                         NVARCHAR (300)  NOT NULL,
    [Bristolmanaged]                                    NVARCHAR (50)   NOT NULL,
    [ContractStartDate]                                 NVARCHAR (50)   NOT NULL,
    [PMIHelpline]                                       NVARCHAR (50)   NOT NULL,
    [ContractLength]                                    NVARCHAR (50)   NOT NULL,
    [SalesType]                                         NVARCHAR (50)   NOT NULL,
    [DependantsCovered]                                 NVARCHAR (50)   NOT NULL,
    [NewContract]                                       NVARCHAR (50)   NOT NULL,
    [AccountManagerName]                                NVARCHAR (50)   NOT NULL,
    [AccountManagerEmailAddress]                        NVARCHAR (50)   NOT NULL,
    [CoordinatorName]                                   NVARCHAR (50)   NOT NULL,
    [CoordinatorEmailAddress]                           NVARCHAR (50)   NOT NULL,
    [FormName]                                          NVARCHAR (50)   NOT NULL,
    [PrimaryCompName]                                   NVARCHAR (50)   NOT NULL,
    [PrimaryCompEmail]                                  NVARCHAR (50)   NOT NULL,
    [PrimaryCompTel]                                    NVARCHAR (50)   NOT NULL,
    [IntermediaryContactName]                           NVARCHAR (50)   NOT NULL,
    [IntermediaryEmail]                                 NVARCHAR (50)   NOT NULL,
    [IntermediaryTel]                                   NVARCHAR (50)   NOT NULL,
    [Intermediary]                                      NVARCHAR (50)   NOT NULL,
    [DirectContactAllowed]                              NVARCHAR (50)   NOT NULL,
    [CompanyFundedEmployeeCapped]                       NVARCHAR (50)   NOT NULL,
    [CompanyFundedDependantCapped]                      NVARCHAR (50)   NOT NULL,
    [CompanyFundedEmployeeUnlimited]                    NVARCHAR (50)   NOT NULL,
    [CompanyFundedDependantUnlimited]                   NVARCHAR (50)   NOT NULL,
    [FlexEmployeeUnlimited]                             NVARCHAR (50)   NOT NULL,
    [FlexDependantUnlimited]                            NVARCHAR (50)   NOT NULL,
    [OverallTotalLives]                                 NVARCHAR (50)   NOT NULL,
    [NumberOfConsultationsPeremployee3CappedunLimited]  NVARCHAR (50)   NOT NULL,
    [NumberofConsultationsperdependant3CappedunLimited] NVARCHAR (50)   NOT NULL,
    [AXAWorkingBody]                                    NVARCHAR (50)   NOT NULL,
    [WorkingBodyExternalProvider]                       NVARCHAR (50)   NOT NULL,
    [AccesstoFastTrack]                                 NVARCHAR (50)   NOT NULL,
    [AdvanceFastTrack]                                  NVARCHAR (50)   NOT NULL,
    [AXAStrongerMinds]                                  NVARCHAR (50)   NOT NULL,
    [AXAEAP]                                            NVARCHAR (50)   NOT NULL,
    [EAPExternalProvider]                               NVARCHAR (50)   NOT NULL,
    [Notes]                                             NVARCHAR (4000) NULL,
    [ModifiedBy]                                        VARCHAR (100)   NULL,
    [ModifiedDate]                                      DATETIME        NULL,
    [IsProcessed]                                       VARCHAR (1)     NULL,
    [ProcessedDate]                                     DATETIME        NULL,
    [BusinessRuleCheck]                                 NVARCHAR (4000) NULL,
    CONSTRAINT [PK_Account_Processing_Manual] PRIMARY KEY CLUSTERED ([LoadId] ASC, [ID] ASC)
);

