CREATE TABLE [dw].[PolicyPatientDetails] (
    [PolicyPatientId]            UNIQUEIDENTIFIER NULL,
    [PolicyPatientName]          NVARCHAR (100)   NULL,
    [StartDate]                  DATE             NULL,
    [StartTime]                  TIME (7)         NULL,
    [CancelledDate]              DATE             NULL,
    [CancelledDateDuePAYGStart]  DATE             NULL,
    [IsCancelledDueToPAYGStart]  SMALLINT         NULL,
    [ExpiryDate]                 DATE             NULL,
    [ExpiryTime]                 TIME (7)         NULL,
    [IsCancelled]                SMALLINT         NULL,
    [IsExpired]                  SMALLINT         NULL,
    [PolicyExpiryDate]           DATE             NULL,
    [PolicyLastRenewalDate]      DATE             NULL,
    [OriginalContactId]          UNIQUEIDENTIFIER NULL,
    [ContactId]                  NVARCHAR (61)    NOT NULL,
    [PolicyId]                   UNIQUEIDENTIFIER NULL,
    [PolicyNumber]               NVARCHAR (100)   NULL,
    [MemberTypeId]               INT              NULL,
    [IncludedPatientDependent]   INT              NULL,
    [IncludedPatientOver18Limit] INT              NULL,
    [PaymentType]                VARCHAR (50)     NULL,
    [AccountId]                  UNIQUEIDENTIFIER NULL,
    [PrimaryContactId]           NVARCHAR (61)    NULL,
    [Status]                     VARCHAR (10)     NULL,
    [HasContactLeft]             INT              NULL,
    [HasPrimaryContactLeft]      INT              NULL,
    [HasLeadRecord]              INT              NULL,
    [IsContactFirstPolicy]       INT              NULL,
    [CancelledDate_Rpt]          DATE             NULL
);

